spring:
  application:
    name: reactive_flux
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pg_db
    username: postgres
    password: admin
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  flyway:
    url: jdbc:postgresql://localhost:5432/pg_db
    user: postgres
    password: admin
logging:
  level:
    org.springframework.r2dbc.core: DEBUG